#ifndef BATTLE_TIMING_H
#define BATTLE_TIMING_H

// Tempos estilo Pokémon Fire Red
#define POKEMON_MESSAGE_SPEED 0.04f
#define POKEMON_HP_ANIMATION_SPEED 1.2f
#define POKEMON_TURN_TRANSITION_TIME 1.0f
#define POKEMON_ATTACK_DELAY 0.5f
#define POKEMON_DAMAGE_FLASH_TIME 0.3f
#define POKEMON_STATUS_MESSAGE_TIME 2.0f

#endif